name: Build and Deploy

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          #cache: 'npm'
          #cache-dependency-path: '/nestjs-api/package-lock.json'
      - name: Install Dependencies
        working-directory: D:\nestjs-api
        run: npm install
      - name: Build Project
        working-directory: D:\nestjs-api
        run: npm run build

  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: self-hosted
    steps:
      - name: Stop current PM2 process by name
        working-directory: D:\nestjs-api
        run: pm2 stop nestjs-api || true
      - name: Start new PM2 process with name
        working-directory: D:\nestjs-api
        run: pm2 start .\dist\main.js --name nestjs-api
      - name: Save PM2 process list
        working-directory: D:\nestjs-api
        run: pm2 save
